### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by john-arvid** [debsahu/HARestAPI#1]
Hi,

Great work on this library!

Is it correct that you are using the HTTP api password to authenticate?
If so, will you change this so it rather uses the long lived access-tokens?
Ref: https://www.home-assistant.io/docs/authentication/providers/#legacy-api-password

**Comment by debsahu** [comment]
Thank you for your kind words. At the time of worrying this library, that was the only option available. I'll look into how to use long lived tokens and get that implemented soon. No promises on the timeline, but will give it a shot soon.

**Comment by john-arvid** [comment]
No problem.
I will follow to see any progress.
I am currently trying to do this myself with just a http client.

**Comment by debsahu** [comment]
Moved from Legacy passwords to long lived access tokens. Could you test it out? Followed instructions from https://developers.home-assistant.io/docs/en/auth_api.html#making-authenticated-requests

**Comment by john-arvid** [comment]
I have tested a confirmed working with curl. But I have problems using ESP8266HTTPClient. Ref: https://community.home-assistant.io/t/long-lived-access-token-with-esp8266httpclient/108847
