### ISSUE TITLE
i have error

### ISSUE THREAD

**Issue by conkhidan** [debsahu/HARestAPI#2]
C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp: In member function 'String HARestAPI::sendGetHA(String, String)':

C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp:82:15: error: expected primary-expression before '=' token

     posturl + = "Authorization: Bearer " + _password + "\r\n";  //long-lived password

               ^

C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp:83:13: error: expected primary-expression before '=' token

   posturl + =   "Content-Type: application/json" + "\r\n" +

             ^

C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp:83:52: error: invalid operands of types 'const char [31]' and 'const char [3]' to binary 'operator+'

   posturl + =   "Content-Type: application/json" + "\r\n" +

                                                    ^

C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp: In member function 'bool HARestAPI::sendPostHA(String, String)':

C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp:158:15: error: expected primary-expression before '=' token

     posturl + = "Authorization: Bearer " + _password + "\r\n";  //long-lived password

               ^

C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp:159:13: error: expected primary-expression before '=' token

   posturl + =   "Content-Type: application/json" + "\r\n" +

             ^

C:\Users\conkhidan\Documents\Arduino\libraries\HARestAPI-master\src\HARestAPI.cpp:159:52: error: invalid operands of types 'const char [31]' and 'const char [3]' to binary 'operator+'

   posturl + =   "Content-Type: application/json" + "\r\n" +

                                                    ^

exit status 1
Error compiling for board NodeMCU 1.0 (ESP-12E Module).

**Comment by Plarkass** [comment]
Hi,

I got same issue on my config

**Comment by debsahu** [comment]
update should fix this.
